repos:
- repo: local
  hooks:
  - id: stylua
    name: StyLua
    language: rust
    entry: stylua
    types: [lua]
    args: ["-"]
  - id: selene
    name: Selene
    language: rust
    entry: selene
    types: [lua]
    args: ["-"]
